if(GPHOTO_INCLUDE_DIR AND GPHOTO_LIBRARIES)
	set(GPHOTO_FIND_QUIETLY TRUE)
endif(GPHOTO_INCLUDE_DIR AND GPHOTO_LIBRARIES)

find_library(GPHOTO_MAIN_LIBRARY gphoto2
	PATHS ${PROJECT_BASE_DIR}/redist/gphoto-2.5.2/lib)

find_library(GPHOTO_PORT_LIBRARY gphoto2_port
	PATHS ${PROJECT_BASE_DIR}/redist/gphoto-2.5.2/lib)

if (GPHOTO_MAIN_LIBRARY AND GPHOTO_PORT_LIBRARY)
	set(GPHOTO_LIBRARIES ${GPHOTO_MAIN_LIBRARY} ${GPHOTO_PORT_LIBRARY})
endif ()

find_path(GPHOTO_INCLUDE_DIR gphoto2/gphoto2.h
	PATH_SUFFIXES include/gphoto2 gphoto2
	PATHS ${PROJECT_BASE_DIR}/redist/gphoto-2.5.2/include)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(Gphoto DEFAULT_MSG GPHOTO_LIBRARIES GPHOTO_INCLUDE_DIR)

MARK_AS_ADVANCED(
	GPHOTO_INCLUDE_DIR
	GPHOTO_LIBRARIES
)
