if(GRAPHICSIPP_INCLUDE_DIR AND GRAPHICSIPP_LIBRARIES)
	set(GRAPHICSIPP_FIND_QUIETLY TRUE)
endif(GRAPHICSIPP_INCLUDE_DIR AND GRAPHICSIPP_LIBRARIES)

find_library(GRAPHICSIPP_LIBRARY Graphics_ipp${BICYCLE_DEBUG_POSTFIX}
			PATHS ${PROJECT_BASE_DIR}/redist/GraphicsIpp/${FULL_QT_VERSION}/lib_${SPEC})

set(GRAPHICSIPP_LIBRARIES ${GRAPHICSIPP_LIBRARY})

find_path(GRAPHICSIPP_INCLUDE_DIR
	modules/gui/multi_graphics/multi_graphics.h
	PATHS ${PROJECT_BASE_DIR}/redist/GraphicsIpp/include)

set ( GRAPHICSIPP_INCLUDE_DIR ${GRAPHICSIPP_INCLUDE_DIR} ${GRAPHICSIPP_INCLUDE_DIR}/modules )

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(GRAPHICSIPP DEFAULT_MSG GRAPHICSIPP_LIBRARIES GRAPHICSIPP_INCLUDE_DIR)

MARK_AS_ADVANCED(
	GRAPHICSIPP_INCLUDE_DIR
	GRAPHICSIPP_LIBRARIES
)

