if(QJSON_INCLUDE_DIR AND QJSON_LIBRARY)
  set(QJSON_FIND_QUIETLY TRUE)
endif(QJSON_INCLUDE_DIR AND QJSON_LIBRARY)

string( TOUPPER ${CMAKE_BUILD_TYPE} CMAKE_BUILD_TYPE_UP )

find_library(QJSON_LIBRARY QJson${CMAKE_${CMAKE_BUILD_TYPE_UP}_POSTFIX} PATHS ${PROJECT_BASE_DIR}/redist/qjson/bin/${SPEC})

set(QJSON_INCLUDE_DIR ${PROJECT_BASE_DIR}/redist/qjson/src/src/qjson)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(QJson DEFAULT_MSG QJSON_LIBRARY QJSON_INCLUDE_DIR)

MARK_AS_ADVANCED(
  QJSON_INCLUDE_DIR
  QJSON_LIBRARY
)
