if(EDSDK_INCLUDE_DIR AND EDSDK_LIBRARY)
	set(EDSDK_FIND_QUIETLY TRUE)
endif(EDSDK_INCLUDE_DIR AND EDSDK_LIBRARY)

find_library(EDSDK_LIBRARY EDSDK.lib
	PATHS ${PROJECT_BASE_DIR}/redist/EDSDK-2.13.2/lib/)

find_path(EDSDK_INCLUDE_DIR EDSDK.h
	PATHS ${PROJECT_BASE_DIR}/redist/EDSDK-2.13.2/include
	)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(EDSDK DEFAULT_MSG EDSDK_LIBRARY EDSDK_INCLUDE_DIR)

MARK_AS_ADVANCED(
	EDSDK_INCLUDE_DIR
	EDSDK_LIBRARY
)
