if(WINDRIVER_INCLUDE_DIR AND WINDRIVER_LIBRARY)
	set(WINDRIVER_FIND_QUIETLY TRUE)
endif(WINDRIVER_INCLUDE_DIR AND WINDRIVER_LIBRARY)

find_library(WINDRIVER_LIBRARY wdapi1001
	NAMES wdapi1001
	PATHS ${PROJECT_BASE_DIR}/redist/Windriver-${HOST}/lib)
#message(STATUS "WINDRIVER_LIBRARY: ${WINDRIVER_LIBRARY}")
find_path(WINDRIVER_INCLUDE_DIR windrvr.h
	${PROJECT_BASE_DIR}/redist/Windriver-${HOST}/include
	)
#message(STATUS "WINDRIVER_INCLUDE_DIR: ${WINDRIVER_INCLUDE_DIR}")
set(WINDRIVER_LIBRARY ${WINDRIVER_LIBRARY} -lsetupapi)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(WinDriver DEFAULT_MSG WINDRIVER_LIBRARY WINDRIVER_INCLUDE_DIR)

MARK_AS_ADVANCED(
	WINDRIVER_INCLUDE_DIR
	WINDRIVER_LIBRARY
)
