if(QHTTPSERVER_INCLUDE_DIR AND QHTTPSERVER_LIBRARY)
  set(QHTTPSERVER_FIND_QUIETLY TRUE)
endif(QHTTPSERVER_INCLUDE_DIR AND QHTTPSERVER_LIBRARY)

string( TOUPPER ${CMAKE_BUILD_TYPE} CMAKE_BUILD_TYPE_UP )
set( QHTTPSERVER_LIBRARY_NAME qhttpserver${CMAKE_${CMAKE_BUILD_TYPE_UP}_POSTFIX}0 )

find_library(QHTTPSERVER_LIBRARY NAMES ${QHTTPSERVER_LIBRARY_NAME} lib${QHTTPSERVER_LIBRARY_NAME} PATHS ${PROJECT_BASE_DIR}/redist/qhttpserver/lib_${SPEC})

set(QHTTPSERVER_INCLUDE_DIR ${PROJECT_BASE_DIR}/redist/qhttpserver/include)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(QHttpServer DEFAULT_MSG QHTTPSERVER_LIBRARY QHTTPSERVER_INCLUDE_DIR)

MARK_AS_ADVANCED(
  QHTTPSERVER_INCLUDE_DIR
  QHTTPSERVER_LIBRARY
)
