if(EXIF_INCLUDE_DIR AND EXIF_LIBRARY)
	set(EXIF_FIND_QUIETLY TRUE)
endif(EXIF_INCLUDE_DIR AND EXIF_LIBRARY)

find_library(EXIF_LIBRARY exif
	PATHS ${PROJECT_BASE_DIR}/redist/libexif/lib)

find_path(EXIF_INCLUDE_DIR libexif/exif-data.h
	PATHS ${PROJECT_BASE_DIR}/redist/libexif/include
	)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(Exif DEFAULT_MSG EXIF_LIBRARY EXIF_INCLUDE_DIR)

MARK_AS_ADVANCED(
	EXIF_INCLUDE_DIR
	EXIF_LIBRARY
)
