if(WINPCAP_INCLUDE_DIR AND WINPCAP_LIBRARY)
	set(WINPCAP_FIND_QUIETLY TRUE)
endif(WINPCAP_INCLUDE_DIR AND WINPCAP_LIBRARY)

find_library(WINPCAP_WPCAP_LIBRARY wpcap
	PATHS ${PROJECT_BASE_DIR}/redist/winpcap/lib)
	
find_library(WINPCAP_PACKET_LIBRARY packet
	PATHS ${PROJECT_BASE_DIR}/redist/winpcap/lib)
	
set(WINPCAP_LIBRARIES ${WINPCAP_WPCAP_LIBRARY} ${WINPCAP_PACKET_LIBRARY})

find_path(WINPCAP_INCLUDE_DIR pcap.h
	${PROJECT_BASE_DIR}/redist/winpcap/include
	)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(WINPCAP DEFAULT_MSG WINPCAP_LIBRARIES WINPCAP_INCLUDE_DIR)

MARK_AS_ADVANCED(
	WINPCAP_INCLUDE_DIR
	WINPCAP_LIBRARIES
)
