if(LIBPCAP_INCLUDE_DIR AND LIBPCAP_LIBRARY)
	set(LIBPCAP_FIND_QUIETLY TRUE)
endif(LIBPCAP_INCLUDE_DIR AND LIBPCAP_LIBRARY)

find_library(LIBPCAP_LIBRARY pcap)

find_path(LIBPCAP_INCLUDE_DIR pcap.h)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LIBPCAP DEFAULT_MSG LIBPCAP_LIBRARY LIBPCAP_INCLUDE_DIR)

MARK_AS_ADVANCED(
	LIBPCAP_INCLUDE_DIR
	LIBPCAP_LIBRARIY
)
