if(NSL_LIBRARY)
	set(NSL_FIND_QUIETLY TRUE)
endif(NSL_LIBRARY)

set(MSVC_DLL .dll)

if(MSVC)
list(APPEND CMAKE_FIND_LIBRARY_SUFFIXES ${MSVC_DLL})
endif()

find_library(NSL_LIBRARY nsl2
	PATHS ${PROJECT_BASE_DIR}/redist/nsl/lib_${SPEC})

if(MSVC)
list(REMOVE_ITEM CMAKE_FIND_LIBRARY_SUFFIXES ${MSVC_DLL})
endif()

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(Nsl2 DEFAULT_MSG NSL_LIBRARY)

MARK_AS_ADVANCED(
	NSL_LIBRARY
)
