if(GPGME_INCLUDE_DIR AND GPGME_LIBRARY)
	set(GPGME_FIND_QUIETLY TRUE)
endif(GPGME_INCLUDE_DIR AND GPGME_LIBRARY)

find_library(GPGME_LIBRARY gpgme)

find_path(GPGME_INCLUDE_DIR gpgme.h)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(GPGME DEFAULT_MSG GPGME_LIBRARY GPGME_INCLUDE_DIR)

MARK_AS_ADVANCED(
	GPGME_INCLUDE_DIR
	GPGME_LIBRARY
)
