if(QTSINGLEAPPLICATION_INCLUDE_DIR AND QTSINGLEAPPLICATION_LIBRARY)
	set(QTSINGLEAPPLICATION_FIND_QUIETLY TRUE)
endif(QTSINGLEAPPLICATION_INCLUDE_DIR AND QTSINGLEAPPLICATION_LIBRARY)

find_library(QTSINGLEAPPLICATION_LIBRARY QtSolutions_SingleApplication-head${BICYCLE_DEBUG_POSTFIX}
    PATHS ${PROJECT_BASE_DIR}/redist/qtsingleapplication/bin/${FULL_QT_VERSION}/lib_${SPEC})

find_path(QTSINGLEAPPLICATION_INCLUDE_DIR QtSingleApplication
	PATHS ${PROJECT_BASE_DIR}/redist/qtsingleapplication/bin/src)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(QtSingleApplication DEFAULT_MSG QTSINGLEAPPLICATION_LIBRARY QTSINGLEAPPLICATION_INCLUDE_DIR)

MARK_AS_ADVANCED(
	QTSINGLEAPPLICATION_INCLUDE_DIR
	QTSINGLEAPPLICATION_LIBRARY
)
