if(ROHC_INCLUDE_DIR AND ROHC_LIBRARIES)
	set(ROHC_FIND_QUIETLY TRUE)
endif(ROHC_INCLUDE_DIR AND ROHC_LIBRARIES)

find_library(ROHC_MAIN_LIBRARY rohc
	PATHS ${PROJECT_BASE_DIR}/redist/rohc/lib_${SPEC})

set(ROHC_LIBRARIES
	${ROHC_MAIN_LIBRARY}
)

find_path(ROHC_INCLUDE_DIR rohc/rohc.h
	PATHS ${PROJECT_BASE_DIR}/redist/rohc/include)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(rohc DEFAULT_MSG ROHC_LIBRARIES ROHC_INCLUDE_DIR)

MARK_AS_ADVANCED(
	ROHC_INCLUDE_DIR
	ROHC_LIBRARIES
)
