if( PANORAMA11_INCLUDE_DIR AND PANORAMA11_LIBRARY )
  set( PANORAMA11_FIND_QUIETLY TRUE )
endif( PANORAMA11_INCLUDE_DIR AND PANORAMA11_LIBRARY )

if( WIN32 )
	set( PANORAMA11_LIBRARY_PATH "${PROJECT_BASE_DIR}/redist/GisTool/Dll" )

	find_library( PANORAMA11_ACCES_LIBRARY gisacces.dll PATHS ${PANORAMA11_LIBRARY_PATH} NO_DEFAULT_PATH )
	find_library( PANORAMA11_VECEX_LIBRARY gisvecex.dll PATHS ${PANORAMA11_LIBRARY_PATH} NO_DEFAULT_PATH )

	set( PANORAMA11_LIBRARIES
		${PANORAMA11_ACCES_LIBRARY}
		${PANORAMA11_VECEX_LIBRARY}
	)

	set( PANORAMA11_INCLUDE_DIR "${PROJECT_BASE_DIR}/redist/Panorama11-win32/gislib11" )

	set( PANORAMA11_INSTALL_FILES
		${PANORAMA11_LIBRARY_PATH}/../MapApi/shape.iml
		${PANORAMA11_LIBRARY_PATH}/../MapApi/s57navy.iml
		${PANORAMA11_LIBRARY_PATH}/../MapApi/rscarmy.iml
		)
else()
	if ( SPEC EQUAL "astra" )
		set( PANORAMA11_LIBRARY_PATH "${PROJECT_BASE_DIR}/redist/Panorama11-astra/usr/lib" )
		set( PANORAMA11_INCLUDE_DIR "${PROJECT_BASE_DIR}/redist/Panorama11-astra/usr/include/qt4" )

		set( PANORAMA11_INSTALL_FILES
			${PANORAMA11_LIBRARY_PATH}/shape.iml64
			${PANORAMA11_LIBRARY_PATH}/s57navy.iml64
			)
	else()
		set( PANORAMA11_LIBRARY_PATH "${PROJECT_BASE_DIR}/redist/Panorama11-msvs/usr/lib" )
		set( PANORAMA11_INCLUDE_DIR "${PROJECT_BASE_DIR}/redist/Panorama11-msvs/usr/lib/qt4/include" )

		set( PANORAMA11_INSTALL_FILES
			${PANORAMA11_LIBRARY_PATH}/shape.iml
			${PANORAMA11_LIBRARY_PATH}/s57navy.iml
			${PANORAMA11_LIBRARY_PATH}/rscarmy.iml
			)
	endif()

	find_library( PANORAMA11_ACCES_LIBRARY qdmapacces PATHS ${PANORAMA11_LIBRARY_PATH} )
	find_library( PANORAMA11_COMPONENTS_LIBRARY mapcomponents PATHS ${PANORAMA11_LIBRARY_PATH} )
	find_library( PANORAMA11_GSSLINK_LIBRARY gsslink PATHS ${PANORAMA11_LIBRARY_PATH} )
	find_library( PANORAMA11_VECEX_LIBRARY qdmapvecex PATHS ${PANORAMA11_LIBRARY_PATH} )
	find_library( PANORAMA11_DL_LIBRARY dl )

	set( PANORAMA11_LIBRARIES
		${PANORAMA11_ACCES_LIBRARY}
		${PANORAMA11_VECEX_LIBRARY}
		${PANORAMA11_COMPONENTS_LIBRARY}
		${PANORAMA11_GSSLINK_LIBRARY}
		${PANORAMA11_DL_LIBRARY}
	)
endif()

include( FindPackageHandleStandardArgs )
find_package_handle_standard_args( Panorama11 DEFAULT_MSG PANORAMA11_LIBRARIES PANORAMA11_INCLUDE_DIR )

mark_as_advanced( PANORAMA11_INCLUDE_DIR PANORAMA11_LIBRARIES )