if(PWGIS_INCLUDE_DIR AND PWGIS_LIBRARIES)
	set(PWGIS_FIND_QUIETLY TRUE)
endif(PWGIS_INCLUDE_DIR AND PWGIS_LIBRARIES)

find_library(PWGIS_CLIENT_LIBRARY PwGisClient${BICYCLE_DEBUG_POSTFIX}
		NAMES PwGisClient${BICYCLE_DEBUG_POSTFIX} PwGisClient${BICYCLE_DEBUG_POSTFIX}1
	PATHS ${PROJECT_BASE_DIR}/redist/PwGis/lib_${SPEC})

find_library(PWGIS_TACTICMAP_LIBRARY PwGisTacticMap${BICYCLE_DEBUG_POSTFIX}
		NAMES PwGisTacticMap${BICYCLE_DEBUG_POSTFIX} PwGisTacticMap${BICYCLE_DEBUG_POSTFIX}1
	PATHS ${PROJECT_BASE_DIR}/redist/PwGis/lib_${SPEC})

find_library(PWGIS_GEOMATHEMATICS_LIBRARY GeoMathematics${BICYCLE_DEBUG_POSTFIX}
		NAMES GeoMathematics${BICYCLE_DEBUG_POSTFIX} GeoMathematics${BICYCLE_DEBUG_POSTFIX}1
	PATHS ${PROJECT_BASE_DIR}/redist/PwGis/lib_${SPEC})

find_library(PWGIS_PWLOGGER_LIBRARY PwLoggerLib${BICYCLE_DEBUG_POSTFIX}
	PATHS ${PROJECT_BASE_DIR}/redist/PwGis/lib_${SPEC})

set(PWGIS_LIBRARIES
		${PWGIS_CLIENT_LIBRARY}
		${PWGIS_TACTICMAP_LIBRARY}
		${PWGIS_GEOMATHEMATICS_LIBRARY}
		${PWGIS_PWLOGGER_LIBRARY}
	)

find_path(PWGIS_INCLUDE_DIR PwGis/pwgiswidget.h
	PATH_SUFFIXES PwGis
	PATHS ${PROJECT_BASE_DIR}/redist/PwGis/include)

#if (PwGis_CORE_INCLUDE_DIR AND PwGis_NETWORK_INCLUDE_DIR)
set (PWGIS_INCLUDE_DIR ${PWGIS_INCLUDE_DIR} ${PWGIS_INCLUDE_DIR}/PwGis ${PWGIS_INCLUDE_DIR}/GeoSearch ${PWGIS_INCLUDE_DIR}/GeoMathematics )
#endif()

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(PWGIS DEFAULT_MSG PWGIS_LIBRARIES PWGIS_INCLUDE_DIR)

MARK_AS_ADVANCED(
	PWGIS_INCLUDE_DIR
	PWGIS_LIBRARIES
)

