if(GCRYPT_INCLUDE_DIR AND GCRYPT_LIBRARY)
	set(GCRYPT_FIND_QUIETLY TRUE)
endif(GCRYPT_INCLUDE_DIR AND GCRYPT_LIBRARY)

find_library(GCRYPT_LIBRARY gcrypt)

find_path(GCRYPT_INCLUDE_DIR gcrypt.h)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(GCRYPT DEFAULT_MSG GCRYPT_LIBRARY GCRYPT_INCLUDE_DIR)

MARK_AS_ADVANCED(
	GCRYPT_INCLUDE_DIR
	GCRYPT_LIBRARY
)
