if(SDL2_INCLUDE_DIR AND SDL2_LIBRARY)
	set(SDL2_FIND_QUIETLY TRUE)
endif(SDL2_INCLUDE_DIR AND SDL2_LIBRARY)

find_library(SDL2_LIBRARY SDL2
	PATHS ${PROJECT_BASE_DIR}/redist/SDL2/lib_${SPEC})

find_path(SDL2_INCLUDE_DIR SDL2/SDL.h
	PATHS ${PROJECT_BASE_DIR}/redist/SDL2/include_${SPEC})

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(SDL2 DEFAULT_MSG SDL2_LIBRARY SDL2_INCLUDE_DIR)

MARK_AS_ADVANCED(
	SDL2_INCLUDE_DIR
	SDL2_LIBRARY
)
