if(PWLOGGER_INCLUDE_DIR AND PWLOGGER_LIBRARY)
	set(PWLOGGER_FIND_QUIETLY TRUE)
endif(PWLOGGER_INCLUDE_DIR AND PWLOGGER_LIBRARY)

find_library(PWLOGGER_LIBRARY PwLoggerLib
	PATHS ${PROJECT_BASE_DIR}/redist/PwLogger/lib_${SPEC})

set (PWLOGGER_INCLUDE_DIR
	${PROJECT_BASE_DIR}/redist/PwLogger/include
	)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(PwLogger DEFAULT_MSG PWLOGGER_LIBRARY PWLOGGER_INCLUDE_DIR)

MARK_AS_ADVANCED(
  PWLOGGER_INCLUDE_DIR
  PWLOGGER_LIBRARY
)
