if(CISCL_INCLUDE_DIR AND CISCL_LIBRARY)
	set(CISCL_FIND_QUIETLY TRUE)
endif(CISCL_INCLUDE_DIR AND CISCL_LIBRARY)

find_library(CISCL_LIBRARY CISCommonLib${BICYCLE_DEBUG_POSTFIX}
	PATHS ${PROJECT_BASE_DIR}/redist/CISCommonLib/${FULL_QT_VERSION}/lib_${SPEC})

find_path(CISCL_INCLUDE_DIR Logger.h
	PATHS ${PROJECT_BASE_DIR}/redist/CISCommonLib/${FULL_QT_VERSION}/include)

if(WIN32)
	set(CISCL_LIBRARY ${CISCL_LIBRARY} -lpsapi)
endif()

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(CISCL DEFAULT_MSG CISCL_LIBRARY CISCL_INCLUDE_DIR)

MARK_AS_ADVANCED(
	CISCL_INCLUDE_DIR
	CISCL_LIBRARY
)
